export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const ADD_TO_CART_USER = "ADD_TO_CART_USER";
export const GET_CART_ITEMS_USER = "GET_CART_ITEMS_USER";
export const REMOVE_CART_ITEM_USER = "REMOVE_CART_ITEM_USER";
export const ON_PURCHASE_PRODUCTS = "ON_PURCHASE_PRODUCTS";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";

export const GET_PRODUCTS_BY_SELL = "GET_PRODUCTS_BY_SELL";
export const GET_PRODUCTS_BY_ARRIVAL = "GET_PRODUCTS_BY_ARRIVAL";
export const GET_GENRES = "GET_GENRES";
export const ADD_GENRE = "ADD_GENRE";
export const GET_PRODUCTS_TO_SHOP = "GET_PRODUCTS_TO_SHOP";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL";

export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
